twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig'] 
    
    globals:
        exampleVariableHijack: '%auctionImagePath%'
        fip: '/u/f/'
        tip: '/u/t/th-'
        # FRONTEND VALIDATION VARIABLES 
        # OFFER MIN AND MAX VALUES
        v_offer_value_min: '0.01'
        v_offer_value_max: '9999999'


when@test:
    twig:
        strict_variables: true
