twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig'] 
    
    globals:
        exampleVariableHijack: '%auctionImagePath%'
        fip: '/u/f/'
        tip: '/u/t/th-'

when@test:
    twig:
        strict_variables: true
