#index:
#    path: /
#    controller: App\Controller\DefaultController::index
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /app
        permanent: true