#index:
#    path: /
#    controller: App\Controller\DefaultController::index
root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: auction-list
        permanent: true